# ~/.tmuxinator/plugin.yml

name: plugin
root: /Users/aviv/GitHub/Rounds/rounds.live/plugin

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

windows:
  - main:
      layout: ab16,202x52,0,0[202x41,0,0,0,202x10,0,42,3]
      panes:
        - vim
        - 
  - build: cd build 
  - logs: tail -f /tmp/nproundsplugin.log 
  - canari: cd "/Applications/Google Chrome Canary.app/Contents/MacOS"; "./Google Chrome Canary" --plugin-startup-dialog
